backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)\

# This line should *not* be indented
media_folder: "assets/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "videos" # Used in routes, e.g., /admin/collections/blog
    label: "Videos" # Used in the UI
    folder: "src/videos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{ slug }}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layout"}
      - {label: "Video Title", name: "videoTitle", widget: "string"}
      - {label: "Author Name", name: "authorName", widget: "string"}
      - {label: "Publish Date", name: "publishedDate", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/{{ slug }}/"}
